// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwxdoxiaeyedktowdmyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3eGRveGlhZXllZGt0b3dkbXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjU0NDMsImV4cCI6MjA1OTUwMTQ0M30.a2XL_0dVkOxImLllwVd_zE__UFGbI8N2-3A9UnTcqU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);