// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
//process.env.REACT_APP_SUPABASE_URL!;


export const supabase = createClient<Database>(
  import.meta.env.VITE_SUPABASE_URL!,
  import.meta.env.VITE_SUPABASE_ANON_KEY!
);

//createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
